### ISSUE TITLE
Draft Feedback

### ISSUE THREAD

**Issue by smeisler** [htwangtw/2021_08_Wang_load-confounds#3]
## Introduction
- "competible" should be changed to compatible 
- "a easy" should be changed to "an easy" in the last sentence
- "output" should be changed to "outputs" in the last sentence

## Progress
- Change to past tense
- remove "ready" from the first sentence

## Strategies

- ICA-AROMA "is", not "are"

## Results

- "Combined" acompcor doesn't refer to anat+temp, but to a combined WM+CSF anatomical mask (so it only applies to acompcor)

**Comment by htwangtw** [comment]
Great catches @smeisler - I am not sure why the compcor part was written like that. Probably my brain melted.
Would you mind fork this repository and make changes on a branch named `sm_feedback`, together with your affiliation details, and finally submit as a PR to this repository?

**Comment by smeisler** [comment]
PR made
